---
skip_commits:
  files:
    - "benchmarks/**"
    - "examples/**"
    - "*.md"
install:
  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - bundle install
before_test:
  - ruby -v
  - gem -v
  - bundle -v
build: off
test_script:
  - bundle exec rake ci
environment:
  matrix:
    - ruby_version: "32-x64"
    - ruby_version: "33-x64"
    - ruby_version: "34-x64"
